obj=allocate_memory.o random_fill_arr.o print_arr.o my_getch.o yes_no.o in_param.o allocate_subarr.o fill_manually.o dynamic_max_subarray.o find_max_subarray.o find_cross_subarray.o print_result.o 
max_subarr_dynamic: main.c $(obj)
	gcc $^ -o $@ -lm

clean: 
	rm *.o
