obj=allocate_memory.o random_fill_arr.o print_arr.o my_getch.o yes_no.o in_param.o save_arr.o find_max_subarray.o find_cross_subarray.o 
max_crossing_subarray: main.c $(obj)
	gcc $^ -o $@ -lm

clean: 
	rm *.o
